print("test1")
print("test2a")
print('::error file=myfile.cpp,line=1,col=5::my error message')
print("test2b")
print("test2a")
print('::group::my group')
print("group1")
print("group2")
print('::endgroup::')
print("test2b")
print("test2a")
print("\033[38;5;1m")
print("Hello red")
print("\033[0m")
print("test2b")
print("test3")
