version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt




#version: 2.1
#jobs:
#  build:
#    docker:
#      - image: mbsimenv/build:latest
#      - name: mbsimenv.build.linux64-ci.latest
#      - entrypoint: bash
#        environment:
#          MBSIMENVSERVERNAME: wwwmfmf.mbsim-env.de
#          STATUSACCESSTOKEN: mfmfdummy
#          MBSIMENVTAGNAME: latest
#    steps:
#      - run:
#        command: /context/entrypoint.py --buildType linux64-ci -j $(nproc) --fmatvecBranch master --hdf5serieBranch master --openmbvBranch master --mbsimBranch master




#init=True
#labels={"buildtype": buildType}
#volumes={
#  'mbsimenv_mbsim-'+buildType+"."+getTagname():  {"bind": "/mbsim-env",    "mode": "rw"},
#  'mbsimenv_report-'+buildType+"."+getTagname(): {"bind": "/mbsim-report", "mode": "rw"},
#  'mbsimenv_ccache.'+getTagname():               {"bind": "/mbsim-ccache", "mode": "rw"},
#  'mbsimenv_state.'+getTagname():                {"bind": "/mbsim-state",  "mode": "rw"},
#}
