version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: mkdir -p $HOME/project/cache/mbsimenv_mbsim && ls -l $HOME/project/cache
      - run: echo $(nproc) >> $HOME/project/test && cat $HOME/project/test
      - store_artifacts:
          path: ~/project/test
          destination: report
##      - restore_cache:
##          name: Restore docker volumes
##          keys:
##           - mbsimenv_cache-linux64-ci.latest
#      - run:
#          name: Prepare docker volume directories
#          no_output_timeout: 1m
#          command: >-
#            mkdir -p $HOME/project/cache/mbsimenv_mbsim
#            $HOME/project/cache/mbsimenv_report
#            $HOME/project/cache/mbsimenv_ccache
#            $HOME/project/cache/mbsimenv_state &&
#            chmod 777 $HOME/project/cache/mbsimenv_mbsim
#            $HOME/project/cache/mbsimenv_report
#            $HOME/project/cache/mbsimenv_ccache
#            $HOME/project/cache/mbsimenv_state
#      - run:
#          name: Pull docker build image
#          no_output_timeout: 5m
#          command: docker pull mbsimenv/build:latest
#      - run:
#          name: Building in docker container
#          no_output_timeout: 3h
#          command: >-
#            docker run --init --label=buildtype=linux64-ci
#            --env=MBSIMENVSERVERNAME=wwwmfmf.mbsim-env.de
#            --env=STATUSACCESSTOKEN=mfmf
#            --env=MBSIMENVTAGNAME=latest
#            -v=$HOME/project/cache/mbsimenv_mbsim:/mbsim-env:rw
#            -v=$HOME/project/cache/mbsimenv_report:/mbsim-report:rw
#            -v=$HOME/project/cache/mbsimenv_ccache:/mbsim-ccache:rw
#            -v=$HOME/project/cache/mbsimenv_state:/mbsim-state:rw
#            mbsimenv/build:latest --buildType linux64-ci -j $(nproc)
#            --fmatvecBranch master --hdf5serieBranch master --openmbvBranch master --mbsimBranch master
##      - save_cache:
##          name: Save docker volumes
##          key: mbsimenv_cache-linux64-ci.latest
##          paths:
##            - $HOME/project/cache
#      - store_artifacts:
#          path: $HOME/project/cache/mbsimenv_report
#          destination: report
#      - store_artifacts:
#          path: $HOME/project/cache/mbsimenv_state
#          destination: state
