name: MBSim-Env
on: [push]
jobs:
  get_ci_branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{steps.branches.outputs.branches}}
    steps:
      - name: "Query MBSim-Env for CI branch combinations"
        id: branches
        run: >
          BRANCHES=$(echo "[{'fmatvec':'master','hdf5serie':'master','openmbv':'master','mbsim':'master'},{'fmatvec':'test','hdf5serie':'master','openmbv':'master','mbsim':'master'}]");
          echo "::set-output name=branches::$BRANCHES"
  build:
    runs-on: ubuntu-latest
    needs: get_ci_branches
    env:
      TAGNAME: staging
      mbsimenvsec_githubStatusAccessToken: ${{secrets.githubStatusAccessToken}}
      mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
      mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
      mbsimenvsec_codecovUploadToken_fmatvec: ${{secrets.codecovUploadToken_fmatvec}}
      mbsimenvsec_codecovUploadToken_hdf5serie: ${{secrets.codecovUploadToken_hdf5serie}}
      mbsimenvsec_codecovUploadToken_openmbv: ${{secrets.codecovUploadToken_openmbv}}
      mbsimenvsec_codecovUploadToken_mbsim: ${{secrets.codecovUploadToken_mbsim}}
    strategy:
      matrix:
        branches: ${{fromJson(needs.get_ci_branches.outputs.branches)}}
        os:
          - buildType: "linux64-ci"
            image: "mbsimenv/build"
          - buildType: "win64-ci"
            image: "mbsimenv/buildwin"
    steps:
      - name: "ccache"
        uses: actions/cache@v2
        with:
          path: ${{env.GITHUB_WORKSPACE}}/ccache
          key: ccache_dir-${{matrix.os.buildType}}
      - run: echo mfmf; cat ${{env.GITHUB_WORKSPACE}}/ccache/ab/file || exit 0
#      - name: "Pull docker build image"
#        run: docker image pull ${{matrix.os.image}}:${{env.TAGNAME}}
      - name: "Run build/examples"
        run: >
          echo "BUILDMFMF ${{matrix.os.buildType}}
                          ${{matrix.os.image}}
                          ${{env.TAGNAME}}
                          ${{matrix.branches.fmatvec}}
                          ${{matrix.branches.hdf5serie}}
                          ${{matrix.branches.openmbv}}
                          ${{matrix.branches.mbsim}}"
#        run: >
#          docker run
#          --init
#          --label buildtype=${{matrix.os.buildType}}
#          --env MBSIMENVDATABASE=www.mbsim-env.de:15432
#          --env MBSIMENVSERVERNAME=wwwstaging.mbsim-env.de
#          --env MBSIMENVTAGNAME=${{env.TAGNAME}}
#          --env MBSIMENVIMAGEID=$(docker image inspect -f "{{.Id}}" ${{matrix.os.image}}:${{env.TAGNAME}})
#          --env mbsimenvsec_githubStatusAccessToken
#          --env mbsimenvsec_djangoSecretKey
#          --env mbsimenvsec_postgresPassword
#          --env mbsimenvsec_codecovUploadToken_fmatvec
#          --env mbsimenvsec_codecovUploadToken_hdf5serie
#          --env mbsimenvsec_codecovUploadToken_openmbv
#          --env mbsimenvsec_codecovUploadToken_mbsim
#          -v ${{env.GITHUB_WORKSPACE}}/ccache:/mbsim-ccache
#          ${{matrix.os.image}}:${{env.TAGNAME}}
#          --buildType ${{matrix.os.buildType}}
#          -j $(nproc)
#          --fmatvecBranch ${{matrix.branches.fmatvec}}
#          --hdf5serieBranch ${{matrix.branches.hdf5serie}}
#          --openmbvBranch ${{matrix.branches.openmbv}}
#          --mbsimBranch ${{matrix.branches.mbsim}}
      - run: docker run -v ${{env.GITHUB_WORKSPACE}}/ccache:/mbsim-ccache alpine sh -c "mkdir -p /mbsim-ccache/ab && date > /mbsim-ccache/ab/file"
      - run: sleep $(($RANDOM%100))
      - run: echo mfmf; cat ${{env.GITHUB_WORKSPACE}}/ccache/ab/file || exit 0
