name: MBSim-Env Build
on:
  push:
  schedule:
    - cron: '36 23 * * *'
jobs:
  build_short:
    name: Build / basic exampels
    uses: ./.github/workflows/mbsim-env-matrixbuild.yml
    with:
      matrixInput: ''
  build_long:
    name: Build / all examples
    uses: ./.github/workflows/mbsim-env-matrixbuild.yml
    with:
      matrixInput: |
        {"data":
          [{
            "branches": 
              {"id": 1, "fmatvecBranch": "master", "hdf5serieBranch": "master", "openmbvBranch": "master", "mbsimBranch": "master"},
            "os":
              {"buildType": "linux64-dailydebug"  , "image": "mbsimenv/build"     ,  "args": "--valgrindExamples"},
          }]
        }
