name: Get Build Matrix
on:
  workflow_call:
    inputs:
      dailyRun:
        required: true
        type: boolean
      pushSource: # JSON string: {"repository": ?, "ref_name": ?, "sha": ?}
        required: true # only required for dailyRun==False, but fromJson is evaluated in all cases and needs to be valid
        type: string
jobs:
  getBuildMatrix:
    name: "."
    runs-on: ubuntu-latest
    steps:
      - name: "Get branch combinations from MBSim-Env server"
        id: matrix
        shell: python
        run: |
          print("${{inputs.pushSource}}")
