name: MBSim-Env Build
on:
  push:
  schedule:
    - cron: '36 23 * * *'
jobs:
  build_short:
    name: Build - basic exampels
    uses: ./.github/workflows/mbsim-env-matrixbuild.yml
    secrets:
      githubStatusAccessToken:
      djangoSecretKey:
      postgresPassword:
      filestoragePassword:
      codecovUploadToken_fmatvec:
      codecovUploadToken_hdf5serie:
      codecovUploadToken_openmbv:
      codecovUploadToken_mbsim:
    with:
      matrixInput: ''
  build_long:
    name: Build - all examples
    uses: ./.github/workflows/mbsim-env-matrixbuild.yml
    if: github.event_name=='schedule'
    secrets:
      githubStatusAccessToken:
      djangoSecretKey:
      postgresPassword:
      filestoragePassword:
      codecovUploadToken_fmatvec:
      codecovUploadToken_hdf5serie:
      codecovUploadToken_openmbv:
      codecovUploadToken_mbsim:
    with:
      matrixInput: |
        {"data":
          [{
            "branches": 
              {"id": 1, "fmatvecBranch": "master", "hdf5serieBranch": "master", "openmbvBranch": "master", "mbsimBranch": "master"},
            "os":
              {"buildType": "linux64-dailydebug"  , "image": "mbsimenv/build"     ,  "args": "--valgrindExamples"},
          }]
        }
