name: MBSim-Env Build
on:
  push:
  schedule:
    - cron: '36 23 * * *'
env:
  # tagname and servername of remote mbsimenv server
  MBSIMENVTAGNAME: staging
  MBSIMENVSERVERNAME: wwwstaging.mbsim-env.de
  # connect to this server:port for www, database and filestorage
  MBSIMENVWWW: www.mbsim-env.de:10443
  MBSIMENVDATABASE: www.mbsim-env.de:15432
  MBSIMENVFILESTORAGE: www.mbsim-env.de:11122
  # get secrets
  mbsimenvsec_githubStatusAccessToken: ${{secrets.githubStatusAccessToken}}
  mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
  mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
  mbsimenvsec_filestoragePassword: ${{secrets.filestoragePassword}}
  mbsimenvsec_codecovUploadToken_fmatvec: ${{secrets.codecovUploadToken_fmatvec}}
  mbsimenvsec_codecovUploadToken_hdf5serie: ${{secrets.codecovUploadToken_hdf5serie}}
  mbsimenvsec_codecovUploadToken_openmbv: ${{secrets.codecovUploadToken_openmbv}}
  mbsimenvsec_codecovUploadToken_mbsim: ${{secrets.codecovUploadToken_mbsim}}
jobs:
  get_matrix:
    name: Get Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrixOutput: ${{steps.matrixStep.outputs.matrixStepOutput}}
    steps:
      - name: "Query MBSim-Env for branch combinations and generate build matrix"
        id: matrixStep
        shell: python
        run: |
          import json
          import requests
          # get repo and branch name
          repo="${{github.repository}}".split("/")[1]
          print("mfmfremove repo="+repo)
          repo="openmbv" #mfmf remove this line
          branch="${{github.ref_name}}"
          sha="${{github.sha}}"
          print("mfmfremove sha="+sha)
          sha="5e1108a787c298b481e31a5dfb2055eb3028f3d0" #mfmf remove this line
          print("Got action for repo="+repo+" branch="+branch+" sha="+sha)
          eventName="${{github.event_name}}"
          # get branch combinations
          if eventName=="push":
            model="CIBranches"
          elif eventName=="schedule":
            model="DailyBranches"
          else:
            raise RuntimeError("Unknown event name")
          response=requests.get("https://${{env.MBSIMENVWWW}}/service/db/getbranchcombi/"+model+"/", verify=False)
          branchCombination=response.json()["data"]
          # check repo
          if eventName=="schedule":
            matrix={"branches": branchCombination,
              "os": [
                {"buildType": "linux64-dailydebug"  , "image": "mbsimenv/build"     ,  "args": "--valgrindExamples"},
                {"buildType": "linux64-dailyrelease", "image": "mbsimenv/build"     ,  "args": ""},
                {"buildType": "win64-dailyrelease"  , "image": "mbsimenv/buildwin64",  "args": ""},
              ]}
          elif eventName=="push":
            # all branch combinations to build
            branches=list(filter(lambda x: x[repo+"Branch"]==branch, branchCombination))
            # if no branch combination is found build this branch with "master" of all other repos
            if len(branches)==0:
              branches=[{"id": 1, "fmatvecBranch": "master", "hdf5serieBranch": "master", "openmbvBranch": "master", "mbsimBranch": "master"}]
              branches[0][repo+"Branch"]=branch+"*"+sha
            else:
              # override repo branch with sha
              for b in branches:
                b[repo+"Branch"]+="*"+sha
            matrix={"branches": branches,
              "os": [
                {"buildType": "linux64-ci", "image": "mbsimenv/build"     , "args": ""},
                {"buildType": "win64-ci"  , "image": "mbsimenv/buildwin64", "args": ""},
              ]}
          # set output
          print("Build matrix:\n"+json.dumps(matrix, indent=2))
          print("::set-output name=matrixStepOutput::"+json.dumps(matrix))
  build:
    uses: ./.github/workflows/mbsim-env-matrixbuild.yml
    with:
      matrixInput: ${{needs.get_matrix.outputs.matrixOutput}}
