name: MBSim-Env
on: [push]
jobs:
  get_ci_branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{steps.branches.outputs.branches}}
    steps:
      - name: "Query MBSim-Env for CI branch combinations"
        id: branches
        run: >
          BRANCHES=$(echo "[{'fmatvec':'master','hdf5serie':'master','openmbv':'master','mbsim':'master'}]");
          echo "::set-output name=branches::$BRANCHES"
  linux64-ci:
    runs-on: ubuntu-latest
    needs: get_ci_branches
    env:
      TAGNAME: staging
      mbsimenvsec_githubStatusAccessToken: ${{secrets.githubStatusAccessToken}}
      mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
      mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
      mbsimenvsec_codecovUploadToken_fmatvec: ${{secrets.codecovUploadToken_fmatvec}}
      mbsimenvsec_codecovUploadToken_hdf5serie: ${{secrets.codecovUploadToken_hdf5serie}}
      mbsimenvsec_codecovUploadToken_openmbv: ${{secrets.codecovUploadToken_openmbv}}
      mbsimenvsec_codecovUploadToken_mbsim: ${{secrets.codecovUploadToken_mbsim}}
    strategy:
      matrix:
        branches: ${{fromJson(needs.get_ci_branches.outputs.branches)}}
        os:
          - buildType: "linux64-ci"
            image: "mbsimenv/build"
          - buildType: "win64-ci"
            image: "mbsimenv/buildwin64"
    steps:
      - name: "dummy"
        run: >
          echo "BUILD ${{matrix.os.buildType}}
                      ${{matrix.os.image}}
                      $TAGNAME
                      ${{matrix.branches.fmatvec}}
                      ${{matrix.branches.hdf5serie}}
                      ${{matrix.branches.openmbv}}
                      ${{matrix.branches.mbsim}}"
#      - name: "Pull docker build image"
#        run: docker image pull ${{matrix.os.image}}:$TAGNAME
#      - name: "Run build/examples"
#        run: >
#          docker run
#          --init
#          --label buildtype=${{matrix.os.buildType}}
#          --env MBSIMENVDATABASE=www.mbsim-env.de:15432
#          --env MBSIMENVSERVERNAME=wwwstaging.mbsim-env.de
#          --env MBSIMENVTAGNAME=$TAGNAME
#          --env MBSIMENVIMAGEID=$(docker image inspect -f "{{.Id}}" ${{matrix.os.image}}:$TAGNAME)
#          --env mbsimenvsec_githubStatusAccessToken
#          --env mbsimenvsec_djangoSecretKey
#          --env mbsimenvsec_postgresPassword
#          --env mbsimenvsec_codecovUploadToken_fmatvec
#          --env mbsimenvsec_codecovUploadToken_hdf5serie
#          --env mbsimenvsec_codecovUploadToken_openmbv
#          --env mbsimenvsec_codecovUploadToken_mbsim
#          ${{matrix.os.image}}:$TAGNAME
#          --buildType ${{matrix.os.buildType}}
#          -j $(nproc)
#          --fmatvecBranch ${{matrix.branches.fmatvec}}
#          --hdf5serieBranch ${{matrix.branches.hdf5serie}}
#          --openmbvBranch ${{matrix.branches.openmbv}}
#          --mbsimBranch ${{matrix.branches.mbsim}}
